# =============================================================================
# DIVE V3 Keycloak - Service Account
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: dive-v3
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: dive-v3
  annotations:
    iam.gke.io/gcp-service-account: dive-v3-keycloak@dive25.iam.gserviceaccount.com



